### ISSUE TITLE
ReNOVo implementation... ValueError: Length of values (14751) does not match length of index (14755)

### ISSUE THREAD

**Issue by se2cheeese** [mazzalab-ieo/renovo#1]
Hello, I tried to run your tool but come up with the following error. 
Could you help me to solve this problem? 

Thank you. 
____________________________________________________________________________________________________________
ReNOVo implementation... 
sys:1: DtypeWarning: Columns (8,9,13,14,35,38,41,44,47,50,53,56,59,64,65,85,86,87,88,118,119,120,121) have mixed types.Specify dtype option on import or set low_memory=False.
sys:1: DtypeWarning: Columns (8,9,13,14,35,38,41,44,47,50,53,56,59,60,64,65,85,86,87,88,118,119,120,121) have mixed types.Specify dtype option on import or set low_memory=False.
Traceback (most recent call last):
  File "./Scripts/Renovo_implementation.py", line 70, in <module>
    original_input["RENOVO_Class"]=RENOVO_Class
  File "/gpfs/home/salee/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 3044, in __setitem__
    self._set_item(key, value)
  File "/gpfs/home/salee/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 3120, in _set_item
    value = self._sanitize_column(key, value)
  File "/gpfs/home/salee/.local/lib/python3.6/site-packages/pandas/core/frame.py", line 3768, in _sanitize_column
    value = sanitize_index(value, self.index)
  File "/gpfs/home/salee/.local/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 748, in sanitize_index
    "Length of values "
ValueError: Length of values (14751) does not match length of index (14755)
DONE!

Output generated! in ./TEST/ReNOVo_output/test_ReNOVo_and_ANNOVAR_implemented.txt

removed ./TEST/temporary/...
removed ./TEST/ReNOVo_output/...
=============================================================================
Thanks for using ReNOVo!
=============================================================================

**Comment by mazzalab-ieo** [comment]
Hi, sorry for the late reply. You have probably already solved the problem but I try to answer anyway. Not being able to see the input dataset I think it is a problem due to repeated genetic variants. One thing that can happen is that after the conversion of the file to avinput by annovar some lines are repeated, or there are malformatted lines. These are only hypotheses based on the reported error (the number of genetic variants processed does not correspond to the number of genetic variants given in input)

**Comment by se2cheeese** [comment]
Thanks for the reply. Unfortunately, I couldn't solve the problem yet. I also thought the problem might be related to duplicates, so I checked duplications before running the tool and modified my vcf file in several ways, which finally failed. Do you have any suggestions to tackle this problem?

**Comment by Emanuele992** [comment]
I know that almost four years have passed (🙈), but we have solved the problem (which thankfully only came up again very rarely). I realize it may no longer be useful, but based on our observations, ReNOVo is not able to annotate variants that have an asterisk (*) in place of the alternative allele. These kinds of variants can appear in VCF files originating from annotations provided by the haplotype caller when multiple samples are annotated at once (https://gatk.broadinstitute.org/hc/en-us/articles/360035531912-Spanning-or-overlapping-deletions-allele). So if you want to try ReNOVo again you simply have to remove those kind of variants.

**Comment by KaramelliSundae** [comment]
@Emanuele992 Thank you so much for your input, i've been trying for more than a week now and i removed every duplicate line but i couldn't figure this out. Really appreciate your follow up comment. I will try right now and remove all variants with asterisk in alternative alleles.

**Comment by Emanuele992** [comment]
Since I’m not receiving any further feedback, I’ll consider this issue closed.

**Comment by KaramelliSundae** [comment]
@Emanuele992 How exactly did you remove asterisks? Can you please share scripts if you have any? 
You can also contact me on telegram if you have https://t.me/@ctivity .

**Comment by KaramelliSundae** [comment]
I tried doing it on my own but i messed up a little bit, really new to programming. it will be really helpful if you can share.

**Comment by Emanuele992** [comment]
Below is an example of a Python script you could use. It reads a multi-sample VCF file and filters out any variants that have an asterisk (`*`) in the `ALT` field. You can run it by piping your input VCF into it and redirecting the output to a new file:

```python
import sys

# Open the VCF file for reading from stdin.
# If preferred, replace sys.stdin with open('my_file.vcf', 'r')
input_vcf = sys.stdin

for line in input_vcf:
    # Print all header lines as they are.
    if line.startswith('#'):
        print(line, end='')
        continue
    
    # Split the line into fields using tab as a delimiter.
    fields = line.strip().split('\t')
    
    # The ALT field is at index 4 (0-based indexing).
    alt = fields[4]
    
    # Check if the alternative allele contains '*'.
    # Only print the line if it does not contain '*'.
    if '*' not in alt:
        print(line, end='')
```

**Usage:**
```bash
python3 filter_vcf.py < input.vcf > output.vcf
```

**Comment by KaramelliSundae** [comment]
Hi @Emanuele992 can you please provide your no-reply github email adress i want to add this script to my fork which our group will use. I want to author you to the commit thank you :)

**Comment by KaramelliSundae** [comment]
@Emanuele992 This issue should be reopened: still getting the same problem after filtering the vcf.
VCF im using:
https://drive.google.com/file/d/1Gs5zLgNYXoX44uzaW5DtjU44-dpHwEnY/view?usp=drive_link
Annovar im using:
https://drive.google.com/file/d/1ojI9M-ij4oP8GdSmsUFurXVG1qV_CyvX/view?usp=drive_link

https://gist.github.com/KaramelliSundae/14234755c09eef2b0ab3301583e88816

`ReNOVo implementation... 
sys:1: DtypeWarning: Columns (0,7,8,9,12,35,38,41,44,47,50,53,56,59,64,65,85,86,87,88,125) have mixed types.Specify dtype option on import or set low_memory=False.
sys:1: DtypeWarning: Columns (0,7,8,9,12,35,38,41,44,47,50,53,56,59,60,64,65,85,86,87,88,125) have mixed types.Specify dtype option on import or set low_memory=False.
Traceback (most recent call last):
  File "/home/dae/Documents/ML/renovo/Scripts/Renovo_implementation.py", line 84, in <module>
    original_input["RENOVO_Class"]=RENOVO_Class
  File "/home/dae/.conda/envs/renovo/lib/python3.6/site-packages/pandas/core/frame.py", line 3044, in __setitem__
    self._set_item(key, value)
  File "/home/dae/.conda/envs/renovo/lib/python3.6/site-packages/pandas/core/frame.py", line 3120, in _set_item
    value = self._sanitize_column(key, value)
  File "/home/dae/.conda/envs/renovo/lib/python3.6/site-packages/pandas/core/frame.py", line 3768, in _sanitize_column
    value = sanitize_index(value, self.index)
  File "/home/dae/.conda/envs/renovo/lib/python3.6/site-packages/pandas/core/internals/construction.py", line 748, in sanitize_index
    "Length of values "
ValueError: Length of values (3021140) does not match length of index (3021601)
DONE!
`

**Comment by KaramelliSundae** [comment]
Note: I filtered the vcf using the script you gave earlier.

**Comment by Emanuele992** [comment]
The script that I gave you was meant to remove only variants with an "*" in the correspondence of the alternative allele. Probably, there are more variants with different types of alternative alleles that Renovo is not able to handle. I'm working on it; I plan to update Renovo's main script in order to maintain those kinds of variants but not provide Renovo classification (putting a simple "NA" in the Renovo columns).

**Comment by Emanuele992** [comment]
@KaramelliSundae I've created a branch in which i manage to solve the problem, can you try it and tell me if it work correctly please? this is the branch Emanuele992-patch-altallele

**Comment by KaramelliSundae** [comment]
![image](https://github.com/user-attachments/assets/02ea8640-c597-4479-a603-3b019e98c663)
All good! Processed entire clinvar database with no errors. Thanks a lot for keeping it updated & the fix

**Comment by Emanuele992** [comment]
ok great! I'll close the issue!
